import { NextResponse } from 'next/server';
export const dynamic = 'force-dynamic';
export async function GET() {
  const airports = [
    { id: 1, name: 'Hartsfield-Jackson Atlanta Intl', iata: 'ATL', icao: 'KATL', lat: 33.64, lng: -84.43, city: 'Atlanta', country: 'USA', runways: 5 },
    { id: 2, name: 'Beijing Capital Intl', iata: 'PEK', icao: 'ZBAA', lat: 40.08, lng: 116.60, city: 'Beijing', country: 'China', runways: 3 },
    { id: 3, name: 'Dubai Intl', iata: 'DXB', icao: 'OMDB', lat: 25.25, lng: 55.37, city: 'Dubai', country: 'UAE', runways: 2 },
    { id: 4, name: 'Tokyo Haneda', iata: 'HND', icao: 'RJTT', lat: 35.55, lng: 139.78, city: 'Tokyo', country: 'Japan', runways: 3 },
    { id: 5, name: 'London Heathrow', iata: 'LHR', icao: 'EGLL', lat: 51.47, lng: -0.45, city: 'London', country: 'UK', runways: 2 },
    { id: 6, name: 'Los Angeles Intl', iata: 'LAX', icao: 'KLAX', lat: 33.94, lng: -118.41, city: 'Los Angeles', country: 'USA', runways: 4 },
    { id: 7, name: "Paris Charles de Gaulle", iata: 'CDG', icao: 'LFPG', lat: 49.01, lng: 2.55, city: 'Paris', country: 'France', runways: 4 },
    { id: 8, name: 'Frankfurt Intl', iata: 'FRA', icao: 'EDDF', lat: 50.04, lng: 8.56, city: 'Frankfurt', country: 'Germany', runways: 4 },
    { id: 9, name: 'Singapore Changi', iata: 'SIN', icao: 'WSSS', lat: 1.36, lng: 103.99, city: 'Singapore', country: 'Singapore', runways: 3 },
    { id: 10, name: 'Amsterdam Schiphol', iata: 'AMS', icao: 'EHAM', lat: 52.31, lng: 4.77, city: 'Amsterdam', country: 'Netherlands', runways: 6 },
    { id: 11, name: 'Incheon Intl', iata: 'ICN', icao: 'RKSI', lat: 37.46, lng: 126.44, city: 'Seoul', country: 'South Korea', runways: 3 },
    { id: 12, name: 'Hong Kong Intl', iata: 'HKG', icao: 'VHHH', lat: 22.31, lng: 113.92, city: 'Hong Kong', country: 'China', runways: 2 },
    { id: 13, name: 'Denver Intl', iata: 'DEN', icao: 'KDEN', lat: 39.86, lng: -104.67, city: 'Denver', country: 'USA', runways: 6 },
    { id: 14, name: 'Istanbul Airport', iata: 'IST', icao: 'LTFM', lat: 41.26, lng: 28.74, city: 'Istanbul', country: 'Turkey', runways: 5 },
    { id: 15, name: 'Dallas-Fort Worth Intl', iata: 'DFW', icao: 'KDFW', lat: 32.90, lng: -97.04, city: 'Dallas', country: 'USA', runways: 7 },
    { id: 16, name: 'Rome Fiumicino', iata: 'FCO', icao: 'LIRF', lat: 41.80, lng: 12.24, city: 'Rome', country: 'Italy', runways: 3 },
    { id: 17, name: 'Milan Malpensa', iata: 'MXP', icao: 'LIMC', lat: 45.63, lng: 8.72, city: 'Milan', country: 'Italy', runways: 2 },
    { id: 18, name: 'Madrid-Barajas', iata: 'MAD', icao: 'LEMD', lat: 40.49, lng: -3.57, city: 'Madrid', country: 'Spain', runways: 4 },
    { id: 19, name: 'Sydney Kingsford Smith', iata: 'SYD', icao: 'YSSY', lat: -33.94, lng: 151.18, city: 'Sydney', country: 'Australia', runways: 3 },
    { id: 20, name: 'Indira Gandhi Intl', iata: 'DEL', icao: 'VIDP', lat: 28.56, lng: 77.10, city: 'Delhi', country: 'India', runways: 3 },
    { id: 21, name: "O'Hare Intl", iata: 'ORD', icao: 'KORD', lat: 41.97, lng: -87.91, city: 'Chicago', country: 'USA', runways: 8 },
    { id: 22, name: 'San Francisco Intl', iata: 'SFO', icao: 'KSFO', lat: 37.62, lng: -122.38, city: 'San Francisco', country: 'USA', runways: 4 },
    { id: 23, name: 'Toronto Pearson Intl', iata: 'YYZ', icao: 'CYYZ', lat: 43.68, lng: -79.63, city: 'Toronto', country: 'Canada', runways: 5 },
    { id: 24, name: 'Bangkok Suvarnabhumi', iata: 'BKK', icao: 'VTBS', lat: 13.69, lng: 100.75, city: 'Bangkok', country: 'Thailand', runways: 2 },
    { id: 25, name: 'Chhatrapati Shivaji Intl', iata: 'BOM', icao: 'VABB', lat: 19.09, lng: 72.87, city: 'Mumbai', country: 'India', runways: 2 },
    { id: 26, name: 'Kuala Lumpur Intl', iata: 'KUL', icao: 'WMKK', lat: 2.75, lng: 101.71, city: 'Kuala Lumpur', country: 'Malaysia', runways: 3 },
    { id: 27, name: 'Soekarno-Hatta Intl', iata: 'CGK', icao: 'WIII', lat: -6.13, lng: 106.66, city: 'Jakarta', country: 'Indonesia', runways: 3 },
    { id: 28, name: 'Munich Airport', iata: 'MUC', icao: 'EDDM', lat: 48.35, lng: 11.79, city: 'Munich', country: 'Germany', runways: 2 },
    { id: 29, name: 'Zurich Airport', iata: 'ZRH', icao: 'LSZH', lat: 47.46, lng: 8.55, city: 'Zurich', country: 'Switzerland', runways: 3 },
    { id: 30, name: 'Vienna Intl', iata: 'VIE', icao: 'LOWW', lat: 48.11, lng: 16.57, city: 'Vienna', country: 'Austria', runways: 2 },
    { id: 31, name: 'Barcelona-El Prat', iata: 'BCN', icao: 'LEBL', lat: 41.30, lng: 2.08, city: 'Barcelona', country: 'Spain', runways: 3 },
    { id: 32, name: 'Copenhagen Airport', iata: 'CPH', icao: 'EKCH', lat: 55.62, lng: 12.66, city: 'Copenhagen', country: 'Denmark', runways: 3 },
    { id: 33, name: 'Oslo Gardermoen', iata: 'OSL', icao: 'ENGM', lat: 60.19, lng: 11.10, city: 'Oslo', country: 'Norway', runways: 2 },
    { id: 34, name: 'Stockholm Arlanda', iata: 'ARN', icao: 'ESSA', lat: 59.65, lng: 17.94, city: 'Stockholm', country: 'Sweden', runways: 3 },
    { id: 35, name: 'Helsinki Vantaa', iata: 'HEL', icao: 'EFHK', lat: 60.32, lng: 24.96, city: 'Helsinki', country: 'Finland', runways: 3 },
    { id: 36, name: 'Dublin Airport', iata: 'DUB', icao: 'EIDW', lat: 53.42, lng: -6.27, city: 'Dublin', country: 'Ireland', runways: 2 },
    { id: 37, name: 'Lisbon Portela', iata: 'LIS', icao: 'LPPT', lat: 38.78, lng: -9.14, city: 'Lisbon', country: 'Portugal', runways: 2 },
    { id: 38, name: 'Athens Eleftherios Venizelos', iata: 'ATH', icao: 'LGAV', lat: 37.94, lng: 23.94, city: 'Athens', country: 'Greece', runways: 2 },
    { id: 39, name: 'São Paulo-Guarulhos', iata: 'GRU', icao: 'SBGR', lat: -23.43, lng: -46.47, city: 'São Paulo', country: 'Brazil', runways: 2 },
    { id: 40, name: 'Mexico City Intl', iata: 'MEX', icao: 'MMMX', lat: 19.44, lng: -99.07, city: 'Mexico City', country: 'Mexico', runways: 2 },
    { id: 41, name: 'Ben Gurion Airport', iata: 'TLV', icao: 'LLBG', lat: 32.01, lng: 34.89, city: 'Tel Aviv', country: 'Israel', runways: 3 },
    { id: 42, name: 'Cairo Intl', iata: 'CAI', icao: 'HECA', lat: 30.12, lng: 31.41, city: 'Cairo', country: 'Egypt', runways: 3 },
  ];
  return NextResponse.json({ airports, total: airports.length, timestamp: new Date().toISOString() });
}
