import type { CctvCamera } from './types';

const TURKEY_CAMERAS: CctvCamera[] = [
  {
    id: 'tr-istanbul-taksim',
    lat: 41.0370, lng: 28.9850,
    name: 'Istanbul — Taksim Square',
    city: 'Istanbul',
    country: 'Turkey',
    stream_url: 'https://www.youtube.com/embed/m3T-nRcjJss?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0',
    stream_type: 'iframe',
    source: 'IBB / YouTube Live',
  },
  {
    id: 'tr-istanbul-bosphorus',
    lat: 41.0250, lng: 29.0050,
    name: 'Istanbul — Bosphorus View',
    city: 'Istanbul',
    country: 'Turkey',
    stream_url: 'https://www.youtube.com/embed/6JQhXFBG8IE?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0',
    stream_type: 'iframe',
    source: 'IBB / YouTube Live',
  },
  {
    id: 'tr-istanbul-hagia-sophia',
    lat: 41.0086, lng: 28.9802,
    name: 'Istanbul — Hagia Sophia / Sultanahmet',
    city: 'Istanbul',
    country: 'Turkey',
    stream_url: 'https://www.youtube.com/embed/vU_hq7UQhB0?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0',
    stream_type: 'iframe',
    source: 'IBB / YouTube Live',
  },
  {
    id: 'tr-istanbul-galata',
    lat: 41.0267, lng: 28.9744,
    name: 'Istanbul — Galata Tower Area',
    city: 'Istanbul',
    country: 'Turkey',
    stream_url: 'https://www.youtube.com/embed/GSh0l4wYerM?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0',
    stream_type: 'iframe',
    source: 'IBB / YouTube Live',
  },
  {
    id: 'tr-istanbul-kadikoy',
    lat: 40.9900, lng: 29.0260,
    name: 'Istanbul — Kadıköy Ferry Terminal',
    city: 'Istanbul',
    country: 'Turkey',
    stream_url: 'https://www.youtube.com/embed/ZOIBGjPLM7E?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0',
    stream_type: 'iframe',
    source: 'IBB / YouTube Live',
  },
  {
    id: 'tr-istanbul-uskudar',
    lat: 41.0230, lng: 29.0150,
    name: 'Istanbul — Üsküdar Waterfront',
    city: 'Istanbul',
    country: 'Turkey',
    stream_url: 'https://www.youtube.com/embed/rgRt5vODVgY?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0',
    stream_type: 'iframe',
    source: 'IBB / YouTube Live',
  },
  {
    id: 'tr-istanbul-15-temmuz',
    lat: 41.0110, lng: 29.0370,
    name: 'Istanbul — 15 July Martyrs Bridge (Bosphorus Bridge)',
    city: 'Istanbul',
    country: 'Turkey',
    external_url: 'https://uygulama.ibb.gov.tr/yuksel/tesisKamera/',
    source: 'IBB Traffic Cameras',
  },
  {
    id: 'tr-istanbul-fsm-bridge',
    lat: 41.0900, lng: 29.0500,
    name: 'Istanbul — Fatih Sultan Mehmet Bridge',
    city: 'Istanbul',
    country: 'Turkey',
    external_url: 'https://uygulama.ibb.gov.tr/yuksel/tesisKamera/',
    source: 'IBB Traffic Cameras',
  },
  {
    id: 'tr-istanbul-yavuz-sultan',
    lat: 41.2000, lng: 29.1100,
    name: 'Istanbul — Yavuz Sultan Selim Bridge',
    city: 'Istanbul',
    country: 'Turkey',
    external_url: 'https://uygulama.ibb.gov.tr/yuksel/tesisKamera/',
    source: 'IBB Traffic Cameras',
  },
  {
    id: 'tr-ankara-kizilay',
    lat: 39.9208, lng: 32.8541,
    name: 'Ankara — Kızılay Square',
    city: 'Ankara',
    country: 'Turkey',
    stream_url: 'https://www.youtube.com/embed/HhLQYqIsMf4?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0',
    stream_type: 'iframe',
    source: 'YouTube Live',
  },
  {
    id: 'tr-ankara-anitkabir',
    lat: 39.9251, lng: 32.8370,
    name: 'Ankara — Anıtkabir',
    city: 'Ankara',
    country: 'Turkey',
    external_url: 'https://www.ankara.bel.tr/cameras',
    source: 'ABB',
  },
  {
    id: 'tr-izmir-kordon',
    lat: 38.4290, lng: 27.1428,
    name: 'Izmir — Kordon Promenade',
    city: 'Izmir',
    country: 'Turkey',
    stream_url: 'https://www.youtube.com/embed/FSW4nT8XgqI?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0',
    stream_type: 'iframe',
    source: 'YouTube Live',
  },
  {
    id: 'tr-antakya-samandag',
    lat: 36.0700, lng: 35.9300,
    name: 'Antakya — Samandağ Coast',
    city: 'Antakya',
    country: 'Turkey',
    external_url: 'https://uygulama.ibb.gov.tr/yuksel/tesisKamera/',
    source: 'IBB',
  },
];

export async function fetchTurkeyCameras(): Promise<CctvCamera[]> {
  return TURKEY_CAMERAS;
}
