import { NextResponse } from 'next/server';
export const dynamic = 'force-dynamic';

const PLATFORMS = [
  { name: 'GitHub', url: 'https://github.com/{u}' },
  { name: 'Twitter/X', url: 'https://x.com/{u}' },
  { name: 'Reddit', url: 'https://reddit.com/user/{u}' },
  { name: 'Instagram', url: 'https://instagram.com/{u}' },
  { name: 'Medium', url: 'https://medium.com/@{u}' },
  { name: 'TikTok', url: 'https://tiktok.com/@{u}' },
  { name: 'YouTube', url: 'https://youtube.com/@{u}' },
  { name: 'Facebook', url: 'https://facebook.com/{u}' },
  { name: 'Telegram', url: 'https://t.me/{u}' },
  { name: 'Keybase', url: 'https://keybase.io/{u}' },
  { name: 'Pinterest', url: 'https://pinterest.com/{u}' },
  { name: 'Twitch', url: 'https://twitch.tv/{u}' },
  { name: 'Steam', url: 'https://steamcommunity.com/id/{u}' },
  { name: 'DeviantArt', url: 'https://deviantart.com/{u}' },
  { name: 'SoundCloud', url: 'https://soundcloud.com/{u}' },
  { name: 'Bluesky', url: 'https://bsky.app/profile/{u}' },
  { name: 'Mastodon.social', url: 'https://mastodon.social/@{u}' },
  { name: 'Threads', url: 'https://threads.net/@{u}' },
  { name: 'LinkedIn', url: 'https://linkedin.com/in/{u}' },
  { name: 'Discord Bio', url: 'https://discords.com/bio/{u}' },
  { name: 'Behance', url: 'https://behance.net/{u}' },
  { name: 'Dribbble', url: 'https://dribbble.com/{u}' },
  { name: 'Flickr', url: 'https://flickr.com/people/{u}' },
  { name: 'Vimeo', url: 'https://vimeo.com/{u}' },
  { name: 'DailyMotion', url: 'https://dailymotion.com/{u}' },
  { name: 'SlideShare', url: 'https://slideshare.net/{u}' },
  { name: 'Scribd', url: 'https://scribd.com/{u}' },
  { name: 'About.me', url: 'https://about.me/{u}' },
  { name: 'AngelList', url: 'https://angel.co/{u}' },
  { name: 'Bitbucket', url: 'https://bitbucket.org/{u}' },
  { name: 'GitLab', url: 'https://gitlab.com/{u}' },
  { name: 'SourceForge', url: 'https://sourceforge.net/u/{u}' },
  { name: 'HackerNews', url: 'https://news.ycombinator.com/user?id={u}' },
  { name: 'ProductHunt', url: 'https://producthunt.com/@{u}' },
  { name: 'IndieHackers', url: 'https://indiehackers.com/{u}' },
  { name: 'DEV.to', url: 'https://dev.to/{u}' },
  { name: 'CodePen', url: 'https://codepen.io/{u}' },
  { name: 'Replit', url: 'https://replit.com/@{u}' },
  { name: 'Glitch', url: 'https://glitch.com/@{u}' },
  { name: 'JSFiddle', url: 'https://jsfiddle.net/user/{u}' },
  { name: 'Stack Overflow', url: 'https://stackoverflow.com/users/{u}' },
  { name: 'Quora', url: 'https://quora.com/profile/{u}' },
  { name: 'Chess.com', url: 'https://chess.com/member/{u}' },
  { name: 'Lichess', url: 'https://lichess.org/@{u}' },
  { name: 'Speedrun.com', url: 'https://speedrun.com/users/{u}' },
  { name: 'MyAnimeList', url: 'https://myanimelist.net/profile/{u}' },
  { name: 'AniList', url: 'https://anilist.co/user/{u}' },
  { name: 'IMDb', url: 'https://imdb.com/user/{u}' },
  { name: 'Letterboxd', url: 'https://letterboxd.com/{u}' },
  { name: 'Last.fm', url: 'https://last.fm/user/{u}' },
  { name: 'Spotify', url: 'https://open.spotify.com/user/{u}' },
  { name: 'Bandcamp', url: 'https://bandcamp.com/{u}' },
  { name: 'Shazam', url: 'https://shazam.com/artist/{u}' },
  { name: 'Mixcloud', url: 'https://mixcloud.com/{u}' },
  { name: 'Rumble', url: 'https://rumble.com/user/{u}' },
  { name: 'Odysee', url: 'https://odysee.com/@{u}' },
  { name: 'TwitchTracker', url: 'https://twitchtracker.com/{u}' },
  { name: 'StreamElements', url: 'https://streamelements.com/{u}' },
  { name: 'Streamlabs', url: 'https://streamlabs.com/{u}' },
  { name: 'Kick', url: 'https://kick.com/{u}' },
  { name: 'Bitchute', url: 'https://bitchute.com/channel/{u}' },
  { name: 'DLive', url: 'https://dlive.tv/{u}' },
  { name: 'Trovo', url: 'https://trovo.live/{u}' },
  { name: 'Shopify Store', url: 'https://{u}.myshopify.com' },
  { name: 'Etsy', url: 'https://etsy.com/shop/{u}' },
  { name: 'Redbubble', url: 'https://redbubble.com/people/{u}' },
  { name: 'eBay', url: 'https://ebay.com/usr/{u}' },
  { name: 'Amazon Wishlist', url: 'https://amazon.com/hz/wishlist/ls/{u}' },
  { name: 'Buy Me a Coffee', url: 'https://buymeacoffee.com/{u}' },
  { name: 'Ko-fi', url: 'https://ko-fi.com/{u}' },
  { name: 'Patreon', url: 'https://patreon.com/{u}' },
  { name: 'Substack', url: 'https://substack.com/@{u}' },
  { name: 'Medium Publication', url: 'https://{u}.medium.com' },
  { name: 'WordPress', url: 'https://{u}.wordpress.com' },
  { name: 'Blogspot', url: 'https://{u}.blogspot.com' },
  { name: 'Wix', url: 'https://{u}.wixsite.com' },
  { name: 'Carrd', url: 'https://{u}.carrd.co' },
  { name: 'Linktree', url: 'https://linktr.ee/{u}' },
  { name: 'Beacons', url: 'https://beacons.ai/{u}' },
  { name: 'Bio.link', url: 'https://bio.link/{u}' },
  { name: 'AllMyLinks', url: 'https://allmylinks.com/{u}' },
  { name: 'Gravatar', url: 'https://gravatar.com/{u}' },
  { name: 'Imgur', url: 'https://imgur.com/user/{u}' },
  { name: '500px', url: 'https://500px.com/{u}' },
  { name: 'Unsplash', url: 'https://unsplash.com/@{u}' },
  { name: 'ArtStation', url: 'https://artstation.com/{u}' },
  { name: 'Behance', url: 'https://behance.net/{u}' },
  { name: 'Cara', url: 'https://cara.app/{u}' },
  { name: 'Fiverr', url: 'https://fiverr.com/{u}' },
  { name: 'Upwork', url: 'https://upwork.com/freelancers/{u}' },
  { name: 'Freelancer', url: 'https://freelancer.com/u/{u}' },
  { name: 'Toptal', url: 'https://toptal.com/experts/{u}' },
  { name: 'Contently', url: 'https://contently.com/{u}' },
  { name: 'Muck Rack', url: 'https://muckrack.com/{u}' },
  { name: 'HubPages', url: 'https://hubpages.com/@{u}' },
  { name: 'Vocal Media', url: 'https://vocal.media/authors/{u}' },
  { name: 'NewsBlur', url: 'https://newsblur.com/profile/{u}' },
  { name: 'Feedly', url: 'https://feedly.com/{u}' },
  { name: 'Instructables', url: 'https://instructables.com/member/{u}' },
  { name: 'Hackaday', url: 'https://hackaday.io/{u}' },
  { name: 'Hackster.io', url: 'https://hackster.io/{u}' },
  { name: 'Thingiverse', url: 'https://thingiverse.com/{u}' },
  { name: 'Printables', url: 'https://printables.com/@{u}' },
  { name: 'Cults3D', url: 'https://cults3d.com/en/users/{u}' },
  { name: 'MyMiniFactory', url: 'https://myminifactory.com/users/{u}' },
  { name: 'PCPartPicker', url: 'https://pcpartpicker.com/user/{u}' },
  { name: 'Tindie', url: 'https://tindie.com/stores/{u}' },
  { name: 'Pocket', url: 'https://pocket.com/@{u}' },
  { name: 'Raindrop.io', url: 'https://raindrop.io/{u}' },
  { name: 'Are.na', url: 'https://are.na/{u}' },
  { name: 'Notion', url: 'https://{u}.notion.site' },
  { name: 'Observable', url: 'https://observablehq.com/@{u}' },
  { name: 'Kaggle', url: 'https://kaggle.com/{u}' },
  { name: 'Hugging Face', url: 'https://huggingface.co/{u}' },
  { name: 'Papers With Code', url: 'https://paperswithcode.com/user/{u}' },
  { name: 'ResearchGate', url: 'https://researchgate.net/profile/{u}' },
  { name: 'Academia.edu', url: 'https://academia.edu/{u}' },
  { name: 'Google Scholar', url: 'https://scholar.google.com/citations?user={u}' },
  { name: 'ORCID', url: 'https://orcid.org/{u}' },
  { name: 'Scratch', url: 'https://scratch.mit.edu/users/{u}' },
  { name: 'Replit', url: 'https://replit.com/@{u}' },
  { name: 'Codewars', url: 'https://codewars.com/users/{u}' },
  { name: 'LeetCode', url: 'https://leetcode.com/{u}' },
  { name: 'HackerRank', url: 'https://hackerrank.com/{u}' },
  { name: 'Codeforces', url: 'https://codeforces.com/profile/{u}' },
  { name: 'TopCoder', url: 'https://topcoder.com/members/{u}' },
  { name: 'CodinGame', url: 'https://codingame.com/profile/{u}' },
  { name: 'Exercism', url: 'https://exercism.org/profiles/{u}' },
  { name: 'TryHackMe', url: 'https://tryhackme.com/p/{u}' },
  { name: 'HackTheBox', url: 'https://hackthebox.com/home/users/profile/{u}' },
  { name: 'Bugcrowd', url: 'https://bugcrowd.com/{u}' },
  { name: 'HackerOne', url: 'https://hackerone.com/{u}' },
  { name: 'Intigriti', url: 'https://intigriti.com/researcher/{u}' },
  { name: 'OpenBugBounty', url: 'https://openbugbounty.org/researchers/{u}' },
  { name: 'CVE MITRE', url: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-{u}' },
  { name: 'Exploit-DB', url: 'https://exploit-db.com/author/{u}' },
  { name: 'PacketStorm', url: 'https://packetstormsecurity.com/files/author/{u}' },
  { name: 'AlienVault OTX', url: 'https://otx.alienvault.com/user/{u}' },
  { name: 'Shodan', url: 'https://shodan.io/user/{u}' },
  { name: 'GreyNoise', url: 'https://greynoise.io/user/{u}' },
  { name: 'AbuseIPDB', url: 'https://abuseipdb.com/user/{u}' },
  { name: 'VirusTotal', url: 'https://virustotal.com/gui/user/{u}' },
  { name: 'urlscan.io', url: 'https://urlscan.io/user/{u}' },
  { name: 'Robtex', url: 'https://robtex.com/dns/{u}' },
  { name: 'DNSlytics', url: 'https://dnslytics.com/user/{u}' },
  { name: 'DomainTools', url: 'https://domaintools.com/{u}' },
  { name: 'WhoisXML', url: 'https://whoisxmlapi.com/user/{u}' },
  { name: 'Spur.us', url: 'https://spur.us/user/{u}' },
  { name: 'IPinfo', url: 'https://ipinfo.io/account/users/{u}' },
  { name: 'BGP.he.net', url: 'https://bgp.he.net/{u}' },
  { name: 'PeeringDB', url: 'https://peeringdb.com/{u}' },
  { name: 'DN42', url: 'https://dn42.dev/user/{u}' },
  { name: 'WireGuard', url: 'https://wireguard.com/{u}' },
  { name: 'Tails', url: 'https://tails.net/{u}' },
  { name: 'Tor Project', url: 'https://torproject.org/user/{u}' },
  { name: 'Signal', url: 'https://signal.org/users/{u}' },
  { name: 'ProtonMail', url: 'https://proton.me/u/{u}' },
  { name: 'Tutanota', url: 'https://tutanota.com/profile/{u}' },
  { name: 'Matrix', url: 'https://matrix.to/@{u}' },
  { name: 'Element', url: 'https://element.io/@{u}' },
  { name: 'Session', url: 'https://session.org/{u}' },
  { name: 'Threema', url: 'https://threema.id/{u}' },
  { name: 'Wickr', url: 'https://wickr.com/{u}' },
  { name: 'Keybase', url: 'https://keybase.io/{u}' },
  { name: 'CryptPad', url: 'https://cryptpad.fr/user/{u}' },
  { name: 'SecureDrop', url: 'https://securedrop.org/user/{u}' },
  { name: 'GlobaLeaks', url: 'https://globaleaks.org/user/{u}' },
  { name: 'Whistleblowers', url: 'https://whistleblowers.org/{u}' },
  { name: 'WikiLeaks', url: 'https://wikileaks.org/{u}' },
  { name: 'OCCRP', url: 'https://occrp.org/profile/{u}' },
  { name: 'ICIJ', url: 'https://icij.org/profile/{u}' },
  { name: 'OpenCorporates', url: 'https://opencorporates.com/officers/{u}' },
  { name: 'Offshore Leaks', url: 'https://offshoreleaks.icij.org/search?q={u}' },
  { name: 'Pandora Papers', url: 'https://pandorapapers.icij.org/search/{u}' },
  { name: 'Paradise Papers', url: 'https://paradisepapers.icij.org/search/{u}' },
  { name: 'Panama Papers', url: 'https://panamapapers.icij.org/search/{u}' },
  { name: 'FinCEN Files', url: 'https://fincenfiles.icij.org/search/{u}' },
  { name: 'LuxLeaks', url: 'https://luxleaks.icij.org/search/{u}' },
  { name: 'Swiss Leaks', url: 'https://swissleaks.icij.org/search/{u}' },
  { name: 'Football Leaks', url: 'https://footballleaks.icij.org/search/{u}' },
  { name: 'DDoSecrets', url: 'https://search.ddosecrets.com/search?q={u}' },
  { name: 'Distributed Denial of Secrets', url: 'https://ddosecrets.com/wiki/Special:Search/{u}' },
  { name: 'WikiLeaks Search', url: 'https://search.wikileaks.org/?q={u}' },
  { name: 'Cryptome', url: 'https://cryptome.org/{u}' },
  { name: 'Globaleaks Platform', url: 'https://globaleaks.org/{u}' },
  { name: 'Hacktivists', url: 'https://hacktivists.net/{u}' },
  { name: 'Anonymous', url: 'https://anonymousplanet.org/{u}' },
  { name: 'Darknet Diaries', url: 'https://darknetdiaries.com/{u}' },
  { name: 'Security BSides', url: 'https://bsides.org/{u}' },
  { name: 'DEF CON', url: 'https://defcon.org/{u}' },
  { name: 'Black Hat', url: 'https://blackhat.com/{u}' },
  { name: 'CCC', url: 'https://ccc.de/{u}' },
  { name: 'HOPE', url: 'https://hope.net/{u}' },
  { name: 'EFF', url: 'https://eff.org/{u}' },
  { name: 'FSF', url: 'https://fsf.org/{u}' },
  { name: 'OSI', url: 'https://opensource.org/user/{u}' },
  { name: 'Apache', url: 'https://apache.org/{u}' },
  { name: 'GNOME', url: 'https://gnome.org/{u}' },
  { name: 'KDE', url: 'https://kde.org/{u}' },
  { name: 'XFCE', url: 'https://xfce.org/{u}' },
  { name: 'MATE', url: 'https://mate-desktop.org/{u}' },
  { name: 'Cinnamon', url: 'https://cinnamon-spices.linuxmint.com/{u}' },
  { name: 'Linux Foundation', url: 'https://linuxfoundation.org/{u}' },
  { name: 'Kernel.org', url: 'https://kernel.org/{u}' },
  { name: 'LWN.net', url: 'https://lwn.net/{u}' },
  { name: 'Phoronix', url: 'https://phoronix.com/{u}' },
  { name: 'DistroWatch', url: 'https://distrowatch.com/{u}' },
  { name: 'Arch Linux', url: 'https://archlinux.org/{u}' },
  { name: 'Debian', url: 'https://debian.org/{u}' },
  { name: 'Ubuntu', url: 'https://ubuntu.com/{u}' },
  { name: 'Fedora', url: 'https://fedoraproject.org/{u}' },
  { name: 'openSUSE', url: 'https://opensuse.org/{u}' },
  { name: 'Gentoo', url: 'https://gentoo.org/{u}' },
  { name: 'NixOS', url: 'https://nixos.org/{u}' },
  { name: 'Void Linux', url: 'https://voidlinux.org/{u}' },
  { name: 'Alpine Linux', url: 'https://alpinelinux.org/{u}' },
  { name: 'Slackware', url: 'https://slackware.com/{u}' },
  { name: 'FreeBSD', url: 'https://freebsd.org/{u}' },
  { name: 'OpenBSD', url: 'https://openbsd.org/{u}' },
  { name: 'NetBSD', url: 'https://netbsd.org/{u}' },
  { name: 'DragonFly BSD', url: 'https://dragonflybsd.org/{u}' },
  { name: 'ReactOS', url: 'https://reactos.org/{u}' },
  { name: 'Haiku', url: 'https://haiku-os.org/{u}' },
  { name: 'Mozilla', url: 'https://mozilla.org/{u}' },
  { name: 'Firefox', url: 'https://firefox.com/{u}' },
  { name: 'Thunderbird', url: 'https://thunderbird.net/{u}' },
  { name: 'LibreOffice', url: 'https://libreoffice.org/{u}' },
  { name: 'GIMP', url: 'https://gimp.org/{u}' },
  { name: 'Inkscape', url: 'https://inkscape.org/{u}' },
  { name: 'Blender', url: 'https://blender.org/{u}' },
  { name: 'Audacity', req: 'https://audacityteam.org/{u}' },
  { name: 'VLC', url: 'https://videolan.org/{u}' },
  { name: 'FFmpeg', url: 'https://ffmpeg.org/{u}' },
  { name: 'OBS Studio', url: 'https://obsproject.com/{u}' },
  { name: 'Krita', url: 'https://krita.org/{u}' },
  { name: 'Godot', url: 'https://godotengine.org/{u}' },
  { name: 'Unity', url: 'https://unity.com/{u}' },
  { name: 'Unreal Engine', url: 'https://unrealengine.com/{u}' },
  { name: 'Epic Games', url: 'https://epicgames.com/{u}' },
  { name: 'Steam', url: 'https://steamcommunity.com/id/{u}' },
  { name: 'GOG', url: 'https://gog.com/u/{u}' },
  { name: 'Humble Bundle', url: 'https://humblebundle.com/{u}' },
  { name: 'itch.io', url: 'https://itch.io/profile/{u}' },
  { name: 'GameJolt', url: 'https://gamejolt.com/@{u}' },
  { name: 'Newgrounds', url: 'https://newgrounds.com/{u}' },
  { name: 'Kongregate', url: 'https://kongregate.com/accounts/{u}' },
  { name: 'Armor Games', url: 'https://armorgames.com/user/{u}' },
  { name: 'CrazyGames', url: 'https://crazygames.com/u/{u}' },
  { name: 'Poki', url: 'https://poki.com/{u}' },
  { name: 'Y8', url: 'https://y8.com/{u}' },
  { name: 'Miniclip', url: 'https://miniclip.com/{u}' },
  { name: 'Pogo', url: 'https://pogo.com/{u}' },
  { name: 'World of Warcraft', url: 'https://worldofwarcraft.com/{u}' },
  { name: 'Battle.net', url: 'https://battle.net/{u}' },
  { name: 'Xbox Live', url: 'https://xbox.com/{u}' },
  { name: 'PlayStation', url: 'https://playstation.com/{u}' },
  { name: 'Nintendo', url: 'https://nintendo.com/{u}' },
  { name: 'Epic Games', url: 'https://epicgames.com/id/{u}' },
  { name: 'Rockstar', url: 'https://rockstargames.com/{u}' },
  { name: 'Riot Games', url: 'https://riotgames.com/{u}' },
  { name: 'Valve', url: 'https://valvesoftware.com/{u}' },
  { name: 'Bethesda', url: 'https://bethesda.net/{u}' },
  { name: 'EA', url: 'https://ea.com/{u}' },
  { name: 'Ubisoft', url: 'https://ubisoft.com/{u}' },
  { name: 'Square Enix', url: 'https://square-enix.com/{u}' },
  { name: 'Capcom', url: 'https://capcom.com/{u}' },
  { name: 'SEGA', url: 'https://sega.com/{u}' },
  { name: 'Konami', url: 'https://konami.com/{u}' },
  { name: 'Bandai Namco', url: 'https://bandainamco.com/{u}' },
  { name: 'Activision', url: 'https://activision.com/{u}' },
  { name: 'Blizzard', url: 'https://blizzard.com/{u}' },
  { name: 'Bungie', url: 'https://bungie.net/{u}' },
  { name: 'CD Projekt', url: 'https://cdprojekt.com/{u}' },
  { name: 'Mojang', url: 'https://minecraft.net/{u}' },
  { name: 'Roblox', url: 'https://roblox.com/user/{u}' },
  { name: 'Fortnite', url: 'https://fortnite.com/{u}' },
  { name: 'Apex Legends', url: 'https://apexlegends.com/{u}' },
  { name: 'Valorant', url: 'https://playvalorant.com/{u}' },
  { name: 'League of Legends', url: 'https://leagueoflegends.com/{u}' },
  { name: 'Dota 2', url: 'https://dota2.com/{u}' },
  { name: 'CS:GO', url: 'https://counter-strike.net/{u}' },
  { name: 'Overwatch', url: 'https://overwatch.com/{u}' },
  { name: 'Rainbow Six', url: 'https://rainbow6.com/{u}' },
  { name: 'Call of Duty', url: 'https://callofduty.com/{u}' },
  { name: 'Battlefield', url: 'https://battlefield.com/{u}' },
  { name: 'Grand Theft Auto', url: 'https://grandtheftauto.com/{u}' },
  { name: 'Red Dead Redemption', url: 'https://reddeadredemption.com/{u}' },
  { name: 'Elder Scrolls', url: 'https://elderscrolls.com/{u}' },
  { name: 'Fallout', url: 'https://fallout.com/{u}' },
  { name: 'Cyberpunk 2077', url: 'https://cyberpunk.net/{u}' },
  { name: 'The Witcher', url: 'https://thewitcher.com/{u}' },
  { name: 'Final Fantasy', url: 'https://finalfantasy.com/{u}' },
  { name: 'Metal Gear', url: 'https://metalgearsolid.com/{u}' },
  { name: 'Resident Evil', url: 'https://residentevil.com/{u}' },
  { name: 'Street Fighter', url: 'https://streetfighter.com/{u}' },
  { name: 'Sonic', url: 'https://sonic.com/{u}' },
  { name: 'Mario', url: 'https://mario.nintendo.com/{u}' },
  { name: 'Zelda', url: 'https://zelda.com/{u}' },
  { name: 'Pokémon', url: 'https://pokemon.com/{u}' },
  { name: 'Animal Crossing', url: 'https://animal-crossing.com/{u}' },
  { name: 'Splatoon', url: 'https://splatoon.nintendo.com/{u}' },
  { name: 'Super Smash Bros', url: 'https://smashbros.com/{u}' },
  { name: 'Minecraft', url: 'https://minecraft.net/{u}' },
  { name: 'Terraria', url: 'https://terraria.org/{u}' },
  { name: 'Stardew Valley', url: 'https://stardewvalley.net/{u}' },
  { name: 'Among Us', url: 'https://amongus.com/{u}' },
  { name: 'FiveM', url: 'https://fivem.net/{u}' },
  { name: 'Garry\'s Mod', url: 'https://gmod.com/{u}' },
  { name: 'Source Engine', url: 'https://sourceengine.com/{u}' },
  { name: 'Unity', url: 'https://unity.com/user/{u}' },
  { name: 'Unreal Engine', url: 'https://unrealengine.com/user/{u}' },
  { name: 'Blender Artists', url: 'https://blenderartists.org/u/{u}' },
  { name: 'Sketchfab', url: 'https://sketchfab.com/{u}' },
  { name: 'TurboSquid', url: 'https://turbosquid.com/{u}' },
  { name: 'CGTrader', url: 'https://cgtrader.com/{u}' },
  { name: 'Renderosity', url: 'https://renderosity.com/{u}' },
  { name: 'DAZ 3D', url: 'https://daz3d.com/{u}' },
  { name: 'Poser', url: 'https://poser.com/{u}' },
  { name: 'Marvelous Designer', url: 'https://marvelousdesigner.com/{u}' },
  { name: 'Clo 3D', url: 'https://clo3d.com/{u}' },
  { name: 'Substance', url: 'https://substance3d.com/{u}' },
  { name: 'Quixel', url: 'https://quixel.com/{u}' },
  { name: 'Megascans', url: 'https://megascans.com/{u}' },
  { name: 'Adobe', url: 'https://adobe.com/{u}' },
  { name: 'Creative Cloud', url: 'https://creativecloud.com/{u}' },
  { name: 'Figma', url: 'https://figma.com/@{u}' },
  { name: 'Sketch', url: 'https://sketch.com/{u}' },
  { name: 'Framer', url: 'https://framer.com/{u}' },
  { name: 'Webflow', url: 'https://webflow.com/@{u}' },
  { name: 'Squarespace', url: 'https://squarespace.com/{u}' },
  { name: 'Wix', url: 'https://wix.com/{u}' },
  { name: 'WordPress.org', url: 'https://profiles.wordpress.org/{u}' },
  { name: 'Drupal', url: 'https://drupal.org/u/{u}' },
  { name: 'Joomla', url: 'https://joomla.org/{u}' },
  { name: 'Moodle', url: 'https://moodle.org/user/{u}' },
  { name: 'Laravel', url: 'https://laravel.io/{u}' },
  { name: 'Symfony', url: 'https://symfony.com/{u}' },
  { name: 'Rails', url: 'https://rubyonrails.org/{u}' },
  { name: 'Django', url: 'https://djangoproject.com/{u}' },
  { name: 'Flask', url: 'https://flask.palletsprojects.com/{u}' },
  { name: 'FastAPI', url: 'https://fastapi.tiangolo.com/{u}' },
  { name: 'Spring', url: 'https://spring.io/{u}' },
  { name: 'Kubernetes', url: 'https://kubernetes.io/{u}' },
  { name: 'Docker', url: 'https://docker.com/{u}' },
  { name: 'Terraform', url: 'https://terraform.io/{u}' },
  { name: 'Ansible', url: 'https://ansible.com/{u}' },
  { name: 'Jenkins', url: 'https://jenkins.io/{u}' },
  { name: 'GitHub Actions', url: 'https://github.com/{u}?tab=actions' },
  { name: 'GitLab CI', url: 'https://gitlab.com/{u}' },
  { name: 'CircleCI', url: 'https://circleci.com/{u}' },
  { name: 'Travis CI', url: 'https://travis-ci.com/{u}' },
  { name: 'Netlify', url: 'https://netlify.com/{u}' },
  { name: 'Vercel', url: 'https://vercel.com/{u}' },
  { name: 'Heroku', url: 'https://heroku.com/{u}' },
  { name: 'DigitalOcean', url: 'https://digitalocean.com/{u}' },
  { name: 'Linode', url: 'https://linode.com/{u}' },
  { name: 'Vultr', url: 'https://vultr.com/{u}' },
  { name: 'AWS', url: 'https://aws.amazon.com/{u}' },
  { name: 'Google Cloud', url: 'https://cloud.google.com/{u}' },
  { name: 'Azure', url: 'https://azure.microsoft.com/{u}' },
  { name: 'Cloudflare', url: 'https://cloudflare.com/{u}' },
  { name: 'Fastly', url: 'https://fastly.com/{u}' },
  { name: 'Akamai', url: 'https://akamai.com/{u}' },
  { name: 'Namecheap', url: 'https://namecheap.com/{u}' },
  { name: 'GoDaddy', url: 'https://godaddy.com/{u}' },
  { name: 'CloudNS', url: 'https://cloudns.com/{u}' },
  { name: 'OVH', url: 'https://ovh.com/{u}' },
  { name: 'Hetzner', url: 'https://hetzner.com/{u}' },
  { name: 'Scaleway', url: 'https://scaleway.com/{u}' },
  { name: 'Contabo', url: 'https://contabo.com/{u}' },
  { name: 'IONOS', url: 'https://ionos.com/{u}' },
  { name: 'Strato', url: 'https://strato.de/{u}' },
  { name: 'Uberspace', url: 'https://uberspace.de/{u}' },
  { name: 'NearlyFreeSpeech', url: 'https://nearlyfreespeech.net/{u}' },
  { name: 'AlwaysData', url: 'https://alwaysdata.com/{u}' },
  { name: 'PythonAnywhere', url: 'https://pythonanywhere.com/user/{u}' },
  { name: 'Replit', url: 'https://replit.com/@{u}' },
  { name: 'Glitch', url: 'https://glitch.com/@{u}' },
  { name: 'Codepen', url: 'https://codepen.io/{u}' },
  { name: 'JSFiddle', url: 'https://jsfiddle.net/user/{u}' },
  { name: 'CodeSandbox', url: 'https://codesandbox.io/u/{u}' },
  { name: 'Stackblitz', url: 'https://stackblitz.com/@{u}' },
  { name: 'Gitpod', url: 'https://gitpod.io/{u}' },
  { name: 'Codespaces', url: 'https://github.com/codespaces/{u}' },
  { name: 'Colab', url: 'https://colab.research.google.com/{u}' },
  { name: 'Kaggle', url: 'https://kaggle.com/{u}' },
  { name: 'Deepnote', url: 'https://deepnote.com/@{u}' },
  { name: 'Hex', url: 'https://hex.tech/{u}' },
  { name: 'Mode Analytics', url: 'https://mode.com/{u}' },
  { name: 'Tableau Public', url: 'https://public.tableau.com/{u}' },
  { name: 'Power BI', url: 'https://powerbi.com/{u}' },
  { name: 'Looker', url: 'https://looker.com/{u}' },
  { name: 'Metabase', url: 'https://metabase.com/{u}' },
  { name: 'Superset', url: 'https://superset.apache.org/{u}' },
  { name: 'Grafana', url: 'https://grafana.com/{u}' },
  { name: 'Prometheus', url: 'https://prometheus.io/{u}' },
  { name: 'InfluxData', url: 'https://influxdata.com/{u}' },
  { name: 'Elastic', url: 'https://elastic.co/{u}' },
  { name: 'Splunk', url: 'https://splunk.com/{u}' },
  { name: 'Datadog', url: 'https://datadoghq.com/{u}' },
  { name: 'New Relic', url: 'https://newrelic.com/{u}' },
  { name: 'Honeycomb', url: 'https://honeycomb.io/{u}' },
  { name: 'Sentry', url: 'https://sentry.io/{u}' },
  { name: 'Rollbar', url: 'https://rollbar.com/{u}' },
  { name: 'BugSnag', url: 'https://bugsnag.com/{u}' },
  { name: 'LogRocket', url: 'https://logrocket.com/{u}' },
  { name: 'FullStory', url: 'https://fullstory.com/{u}' },
  { name: 'Hotjar', url: 'https://hotjar.com/{u}' },
  { name: 'Mixpanel', url: 'https://mixpanel.com/{u}' },
  { name: 'Amplitude', url: 'https://amplitude.com/{u}' },
  { name: 'Segment', url: 'https://segment.com/{u}' },
  { name: 'PostHog', url: 'https://posthog.com/{u}' },
  { name: 'Plausible', url: 'https://plausible.io/{u}' },
  { name: 'Fathom', url: 'https://fathomanalytics.com/{u}' },
  { name: 'Matomo', url: 'https://matomo.org/{u}' },
  { name: 'Google Analytics', url: 'https://analytics.google.com/{u}' },
  { name: 'Google Ads', url: 'https://ads.google.com/{u}' },
  { name: 'Google Search Console', url: 'https://search.google.com/{u}' },
  { name: 'Google Tag Manager', url: 'https://tagmanager.google.com/{u}' },
  { name: 'Google Optimize', url: 'https://optimize.google.com/{u}' },
  { name: 'Google Data Studio', url: 'https://datastudio.google.com/{u}' },
  { name: 'Google My Business', url: 'https://business.google.com/{u}' },
  { name: 'Google Play Console', url: 'https://play.google.com/console/{u}' },
  { name: 'Apple Developer', url: 'https://developer.apple.com/{u}' },
  { name: 'App Store Connect', url: 'https://appstoreconnect.apple.com/{u}' },
  { name: 'Microsoft Partner', url: 'https://partner.microsoft.com/{u}' },
  { name: 'AWS Console', url: 'https://console.aws.amazon.com/{u}' },
  { name: 'Azure Portal', url: 'https://portal.azure.com/{u}' },
  { name: 'GCP Console', url: 'https://console.cloud.google.com/{u}' },
  { name: 'DigitalOcean Console', url: 'https://cloud.digitalocean.com/{u}' },
  { name: 'Linode Console', url: 'https://cloud.linode.com/{u}' },
  { name: 'Vultr Console', url: 'https://my.vultr.com/{u}' },
  { name: 'Hetzner Console', url: 'https://console.hetzner.cloud/{u}' },
  { name: 'Scaleway Console', url: 'https://console.scaleway.com/{u}' },
  { name: 'OVH Console', url: 'https://ovh.com/manager/{u}' },
  { name: 'Namecheap Console', url: 'https://ap.www.namecheap.com/{u}' },
  { name: 'Cloudflare Dashboard', url: 'https://dash.cloudflare.com/{u}' },
  { name: 'Vercel Dashboard', url: 'https://vercel.com/dashboard/{u}' },
  { name: 'Netlify Dashboard', url: 'https://app.netlify.com/{u}' },
  { name: 'Heroku Dashboard', url: 'https://dashboard.heroku.com/{u}' },
  { name: 'Render Dashboard', url: 'https://dashboard.render.com/{u}' },
  { name: 'Railway Dashboard', url: 'https://railway.app/{u}' },
  { name: 'Fly.io Dashboard', url: 'https://fly.io/{u}' },
  { name: 'Koyeb Dashboard', url: 'https://koyeb.com/{u}' },
  { name: 'Northflank', url: 'https://northflank.com/{u}' },
  { name: 'Porter', url: 'https://porter.run/{u}' },
  { name: 'Kubermatic', url: 'https://kubermatic.com/{u}' },
  { name: 'Platform9', url: 'https://platform9.com/{u}' },
  { name: 'Rancher', url: 'https://rancher.com/{u}' },
  { name: 'OpenShift', url: 'https://openshift.com/{u}' },
  { name: 'Tanzu', url: 'https://tanzu.vmware.com/{u}' },
  { name: 'Red Hat', url: 'https://redhat.com/{u}' },
  { name: 'SUSE', url: 'https://suse.com/{u}' },
  { name: 'Canonical', url: 'https://canonical.com/{u}' },
  { name: 'Ubuntu One', url: 'https://login.ubuntu.com/{u}' },
  { name: 'Launchpad', url: 'https://launchpad.net/~{u}' },
  { name: 'OpenHub', url: 'https://openhub.net/accounts/{u}' },
  { name: 'Ohloh', url: 'https://ohloh.net/{u}' },
  { name: 'CII Best Practices', url: 'https://bestpractices.coreinfrastructure.org/{u}' },
  { name: 'LFX', url: 'https://lfx.linuxfoundation.org/{u}' },
  { name: 'CNCF', url: 'https://cncf.io/{u}' },
  { name: 'OpenSSF', url: 'https://openssf.org/{u}' },
  { name: 'OWASP', url: 'https://owasp.org/{u}' },
  { name: 'ISO', url: 'https://iso.org/{u}' },
  { name: 'NIST', url: 'https://nist.gov/{u}' },
  { name: 'MITRE', url: 'https://mitre.org/{u}' },
  { name: 'CISA', url: 'https://cisa.gov/{u}' },
  { name: 'ENISA', url: 'https://enisa.europa.eu/{u}' },
  { name: 'NCSC', url: 'https://ncsc.gov.uk/{u}' },
  { name: 'BSI', url: 'https://bsi.bund.de/{u}' },
  { name: 'ANSSI', url: 'https://ssi.gouv.fr/{u}' },
  { name: 'CERT', url: 'https://cert.org/{u}' },
  { name: 'US-CERT', url: 'https://us-cert.cisa.gov/{u}' },
  { name: 'J-CERT', url: 'https://jcert.org/{u}' },
  { name: 'NCSC-NL', url: 'https://ncsc.nl/{u}' },
  { name: 'NCSC-FI', url: 'https://ncsc.fi/{u}' },
  { name: 'CyberSwat', url: 'https://cyberswat.org/{u}' },
  { name: 'Shadowserver', url: 'https://shadowserver.org/{u}' },
  { name: 'Spamhaus', url: 'https://spamhaus.org/{u}' },
  { name: 'Team Cymru', url: 'https://team-cymru.com/{u}' },
  { name: 'CleanTalk', url: 'https://cleantalk.org/{u}' },
  { name: 'StopForumSpam', url: 'https://stopforumspam.com/{u}' },
  { name: 'AbuseAtlas', url: 'https://abuseatlas.com/{u}' },
  { name: 'URLhaus', url: 'https://urlhaus.abuse.ch/{u}' },
  { name: 'MalwareBazaar', url: 'https://bazaar.abuse.ch/{u}' },
  { name: 'ThreatFox', url: 'https://threatfox.abuse.ch/{u}' },
  { name: 'YARAify', url: 'https://yaraify.abuse.ch/{u}' },
  { name: 'Feodo Tracker', url: 'https://feodo.abuse.ch/{u}' },
  { name: 'SSL Blacklist', url: 'https://sslbl.abuse.ch/{u}' },
  { name: 'Cybercrime Tracker', url: 'https://cybercrime-tracker.net/{u}' },
  { name: 'VX Underground', url: 'https://vx-underground.org/{u}' },
  { name: 'Malpedia', url: 'https://malpedia.caad.fkie.fraunhofer.de/{u}' },
  { name: 'MalShare', url: 'https://malshare.com/{u}' },
  { name: 'Hybrid Analysis', url: 'https://hybrid-analysis.com/{u}' },
  { name: 'Any.Run', url: 'https://any.run/{u}' },
  { name: 'Joe Sandbox', url: 'https://joesandbox.com/{u}' },
  { name: 'Cuckoo Sandbox', url: 'https://cuckoosandbox.org/{u}' },
  { name: 'CAPE', url: 'https://capev2.com/{u}' },
  { name: 'Cylance', url: 'https://cylance.com/{u}' },
  { name: 'CrowdStrike', url: 'https://crowdstrike.com/{u}' },
  { name: 'Mandiant', url: 'https://mandiant.com/{u}' },
  { name: 'FireEye', url: 'https://fireeye.com/{u}' },
  { name: 'Kaspersky', url: 'https://kaspersky.com/{u}' },
  { name: 'ESET', url: 'https://eset.com/{u}' },
  { name: 'Avast', url: 'https://avast.com/{u}' },
  { name: 'McAfee', url: 'https://mcafee.com/{u}' },
  { name: 'Symantec', url: 'https://symantec.com/{u}' },
  { name: 'Trend Micro', url: 'https://trendmicro.com/{u}' },
  { name: 'Palo Alto', url: 'https://paloaltonetworks.com/{u}' },
  { name: 'Fortinet', url: 'https://fortinet.com/{u}' },
  { name: 'Check Point', url: 'https://checkpoint.com/{u}' },
  { name: 'Sophos', url: 'https://sophos.com/{u}' },
  { name: 'Bitdefender', url: 'https://bitdefender.com/{u}' },
  { name: 'Malwarebytes', url: 'https://malwarebytes.com/{u}' },
  { name: 'Emsisoft', url: 'https://emsisoft.com/{u}' },
  { name: 'F-Secure', url: 'https://f-secure.com/{u}' },
  { name: 'G Data', url: 'https://gdata.com/{u}' },
  { name: 'Avira', url: 'https://avira.com/{u}' },
  { name: 'BullGuard', url: 'https://bullguard.com/{u}' },
  { name: 'Norton', url: 'https://norton.com/{u}' },
  { name: 'ZoneAlarm', url: 'https://zonealarm.com/{u}' },
  { name: 'Comodo', url: 'https://comodo.com/{u}' },
  { name: 'Webroot', url: 'https://webroot.com/{u}' },
  { name: 'VIPRE', url: 'https://vipre.com/{u}' },
  { name: 'TotalAV', url: 'https://totalav.com/{u}' },
  { name: 'PC Matic', url: 'https://pcmatic.com/{u}' },
  { name: 'IObit', url: 'https://iobit.com/{u}' },
  { name: 'CCleaner', url: 'https://ccleaner.com/{u}' },
  { name: 'Revo Uninstaller', url: 'https://revouninstaller.com/{u}' },
  { name: 'WiseCleaner', url: 'https://wisecleaner.com/{u}' },
  { name: 'Glary Utilities', url: 'https://glarysoft.com/{u}' },
  { name: 'Advanced SystemCare', url: 'https://advancedsystemcare.com/{u}' },
  { name: 'TuneUp Utilities', url: 'https://tuneup-utilities.com/{u}' },
  { name: 'Auslogics', url: 'https://auslogics.com/{u}' },
  { name: 'Defraggler', url: 'https://defraggler.com/{u}' },
  { name: 'Recuva', url: 'https://recuva.com/{u}' },
  { name: 'Speccy', url: 'https://speccy.com/{u}' },
  { name: 'HWMonitor', url: 'https://hwmonitor.com/{u}' },
  { name: 'CPU-Z', url: 'https://cpuid.com/{u}' },
  { name: 'GPU-Z', url: 'https://techpowerup.com/{u}' },
  { name: '3DMark', url: 'https://3dmark.com/{u}' },
  { name: 'PCMark', url: 'https://pcmark.com/{u}' },
  { name: 'Geekbench', url: 'https://geekbench.com/{u}' },
  { name: 'Cinebench', url: 'https://cinebench.com/{u}' },
  { name: 'Prime95', url: 'https://prime95.com/{u}' },
  { name: 'OCCT', url: 'https://occt.com/{u}' },
  { name: 'FurMark', url: 'https://furmark.com/{u}' },
  { name: 'Unigine', url: 'https://unigine.com/{u}' },
  { name: 'Valley Benchmark', url: 'https://valley.unigine.com/{u}' },
  { name: 'Superposition', url: 'https://superposition.unigine.com/{u}' },
  { name: 'Heaven Benchmark', url: 'https://heaven.unigine.com/{u}' },
  { name: 'Novabench', url: 'https://novabench.com/{u}' },
  { name: 'PassMark', url: 'https://passmark.com/{u}' },
  { name: 'UserBenchmark', url: 'https://userbenchmark.com/{u}' },
  { name: 'MSI Afterburner', url: 'https://msiab.com/{u}' },
  { name: 'EVGA Precision', url: 'https://evga.com/{u}' },
  { name: 'ASUS GPU Tweak', url: 'https://asus.com/{u}' },
  { name: 'Gigabyte', url: 'https://gigabyte.com/{u}' },
  { name: 'MSI', url: 'https://msi.com/{u}' },
  { name: 'ASRock', url: 'https://asrock.com/{u}' },
  { name: 'Intel', url: 'https://intel.com/{u}' },
  { name: 'AMD', url: 'https://amd.com/{u}' },
  { name: 'NVIDIA', url: 'https://nvidia.com/{u}' },
  { name: 'Apple', url: 'https://apple.com/{u}' },
  { name: 'Samsung', url: 'https://samsung.com/{u}' },
  { name: 'Google', url: 'https://google.com/{u}' },
  { name: 'Microsoft', url: 'https://microsoft.com/{u}' },
  { name: 'Amazon', url: 'https://amazon.com/{u}' },
  { name: 'Meta', url: 'https://meta.com/{u}' },
  { name: 'Netflix', url: 'https://netflix.com/{u}' },
  { name: 'Spotify', url: 'https://spotify.com/{u}' },
  { name: 'Uber', url: 'https://uber.com/{u}' },
  { name: 'Airbnb', url: 'https://airbnb.com/{u}' },
  { name: 'Tesla', url: 'https://tesla.com/{u}' },
  { name: 'SpaceX', url: 'https://spacex.com/{u}' },
  { name: 'OpenAI', url: 'https://openai.com/{u}' },
  { name: 'Anthropic', url: 'https://anthropic.com/{u}' },
  { name: 'DeepMind', url: 'https://deepmind.com/{u}' },
  { name: 'Hugging Face', url: 'https://huggingface.co/{u}' },
  { name: 'Replicate', url: 'https://replicate.com/{u}' },
  { name: 'Runway', url: 'https://runwayml.com/{u}' },
  { name: 'Midjourney', url: 'https://midjourney.com/{u}' },
  { name: 'Stability AI', url: 'https://stability.ai/{u}' },
  { name: 'ElevenLabs', url: 'https://elevenlabs.io/{u}' },
  { name: 'AssemblyAI', url: 'https://assemblyai.com/{u}' },
  { name: 'Deepgram', url: 'https://deepgram.com/{u}' },
  { name: 'Descript', url: 'https://descript.com/{u}' },
  { name: 'Otter.ai', url: 'https://otter.ai/{u}' },
  { name: 'Fireflies.ai', url: 'https://fireflies.ai/{u}' },
  { name: 'Notion', url: 'https://notion.so/{u}' },
  { name: 'Obsidian', url: 'https://obsidian.md/{u}' },
  { name: 'Roam Research', url: 'https://roamresearch.com/{u}' },
  { name: 'Logseq', url: 'https://logseq.com/{u}' },
  { name: 'Dendron', url: 'https://dendron.so/{u}' },
  { name: 'Foam', url: 'https://foambubble.github.io/{u}' },
  { name: 'Mem', url: 'https://mem.ai/{u}' },
  { name: 'Reflect', url: 'https://reflect.app/{u}' },
  { name: 'Capacities', url: 'https://capacities.io/{u}' },
  { name: 'Anytype', url: 'https://anytype.io/{u}' },
  { name: 'Coda', url: 'https://coda.io/{u}' },
  { name: 'ClickUp', url: 'https://clickup.com/{u}' },
  { name: 'Notion', url: 'https://notion.so/{u}' },
  { name: 'Monday.com', url: 'https://monday.com/{u}' },
  { name: 'Asana', url: 'https://asana.com/{u}' },
  { name: 'Trello', url: 'https://trello.com/{u}' },
  { name: 'Jira', url: 'https://jira.com/{u}' },
  { name: 'Linear', url: 'https://linear.app/{u}' },
  { name: 'Height', url: 'https://height.app/{u}' },
  { name: 'Basecamp', url: 'https://basecamp.com/{u}' },
  { name: 'Slack', url: 'https://slack.com/{u}' },
  { name: 'Discord', url: 'https://discord.com/{u}' },
  { name: 'Teams', url: 'https://teams.microsoft.com/{u}' },
  { name: 'Zoom', url: 'https://zoom.us/{u}' },
  { name: 'Google Meet', url: 'https://meet.google.com/{u}' },
  { name: 'Jitsi', url: 'https://jitsi.org/{u}' },
  { name: 'Whereby', url: 'https://whereby.com/{u}' },
  { name: 'Around', url: 'https://around.co/{u}' },
  { name: 'Skype', url: 'https://skype.com/{u}' },
  { name: 'WhatsApp', url: 'https://whatsapp.com/{u}' },
  { name: 'Telegram', url: 'https://t.me/{u}' },
  { name: 'Signal', url: 'https://signal.org/{u}' },
  { name: 'Wire', url: 'https://wire.com/{u}' },
  { name: 'Element', url: 'https://element.io/{u}' },
  { name: 'Matrix', url: 'https://matrix.org/{u}' },
  { name: 'Rocket.Chat', url: 'https://rocket.chat/{u}' },
  { name: 'Mattermost', url: 'https://mattermost.com/{u}' },
  { name: 'Zulip', url: 'https://zulip.com/{u}' },
  { name: 'Keybase', url: 'https://keybase.io/{u}' },
  { name: 'Session', url: 'https://getsession.org/{u}' },
  { name: 'Threema', url: 'https://threema.ch/{u}' },
  { name: 'Wickr', url: 'https://wickr.com/{u}' },
  { name: 'ProtonMail', url: 'https://proton.me/{u}' },
  { name: 'Tutanota', url: 'https://tutanota.com/{u}' },
  { name: 'Mailbox.org', url: 'https://mailbox.org/{u}' },
  { name: 'Posteo', url: 'https://posteo.de/{u}' },
  { name: 'Runbox', url: 'https://runbox.com/{u}' },
  { name: 'FastMail', url: 'https://fastmail.com/{u}' },
  { name: 'Hey', url: 'https://hey.com/{u}' },
  { name: 'ProtonMail', url: 'https://protonmail.com/{u}' },
  { name: 'Skiff', url: 'https://skiff.com/{u}' },
  { name: 'CTemplar', url: 'https://ctemplar.com/{u}' },
  { name: 'Disroot', url: 'https://disroot.org/{u}' },
  { name: 'RiseUp', url: 'https://riseup.net/{u}' },
  { name: 'Autistici', url: 'https://autistici.org/{u}' },
  { name: 'Inventati', url: 'https://inventati.org/{u}' },
  { name: 'Cock.li', url: 'https://cock.li/{u}' },
  { name: 'AirMail', url: 'https://airmail.cc/{u}' },
  { name: 'Guerrilla Mail', url: 'https://guerrillamail.com/{u}' },
  { name: 'Temp Mail', url: 'https://tempmail.com/{u}' },
  { name: '10 Minute Mail', url: 'https://10minutemail.com/{u}' },
  { name: 'Mailinator', url: 'https://mailinator.com/{u}' },
  { name: 'YOPmail', url: 'https://yopmail.com/{u}' },
  { name: 'Spamgourmet', url: 'https://spamgourmet.com/{u}' },
  { name: 'Trashmail', url: 'https://trashmail.com/{u}' },
  { name: 'Burner Mail', url: 'https://burnermail.io/{u}' },
  { name: 'SimpleLogin', url: 'https://simplelogin.io/{u}' },
  { name: 'Addy.io', url: 'https://addy.io/{u}' },
  { name: 'Firefox Relay', url: 'https://relay.firefox.com/{u}' },
  { name: 'DuckDuckGo Email', url: 'https://duckduckgo.com/email/{u}' },
  { name: 'Apple Hide My Email', url: 'https://apple.com/hide-my-email/{u}' },
  { name: 'ICloud Mail', url: 'https://icloud.com/mail/{u}' },
  { name: 'Outlook', url: 'https://outlook.com/{u}' },
  { name: 'Gmail', url: 'https://gmail.com/{u}' },
  { name: 'Yahoo Mail', url: 'https://mail.yahoo.com/{u}' },
  { name: 'AOL Mail', url: 'https://mail.aol.com/{u}' },
  { name: 'GMX', url: 'https://gmx.com/{u}' },
  { name: 'Mail.com', url: 'https://mail.com/{u}' },
  { name: 'Zoho Mail', url: 'https://zoho.com/mail/{u}' },
  { name: 'Yandex Mail', url: 'https://mail.yandex.com/{u}' },
  { name: 'Mail.ru', url: 'https://mail.ru/{u}' },
  { name: 'Rambler', url: 'https://rambler.ru/{u}' },
  { name: 'Tutanota', url: 'https://tutanota.com/{u}' },
  { name: 'Posteo', url: 'https://posteo.de/{u}' },
  { name: 'Mailfence', url: 'https://mailfence.com/{u}' },
  { name: 'StartMail', url: 'https://startmail.com/{u}' },
  { name: 'CounterMail', url: 'https://countermail.com/{u}' },
  { name: 'Hushmail', url: 'https://hushmail.com/{u}' },
  { name: 'Neomailbox', url: 'https://neomailbox.com/{u}' },
  { name: 'ScryptMail', url: 'https://scryptmail.com/{u}' },
  { name: 'Lavabit', url: 'https://lavabit.com/{u}' },
  { name: 'Soverin', url: 'https://soverin.net/{u}' },
  { name: 'Kolab Now', url: 'https://kolabnow.com/{u}' },
  { name: 'Migadu', url: 'https://migadu.com/{u}' },
  { name: 'PurelyMail', url: 'https://purelymail.com/{u}' },
  { name: 'MXRoute', url: 'https://mxroute.com/{u}' },
  { name: 'Namecheap Email', url: 'https://namecheap.com/email/{u}' },
  { name: 'Google Workspace', url: 'https://workspace.google.com/{u}' },
  { name: 'Microsoft 365', url: 'https://microsoft365.com/{u}' },
  { name: 'Zoho Workplace', url: 'https://zoho.com/workplace/{u}' },
  { name: 'Yandex 360', url: 'https://360.yandex.com/{u}' },
  { name: 'Mail.ru for Business', url: 'https://biz.mail.ru/{u}' },
  { name: 'Titan Email', url: 'https://titan.email/{u}' },
  { name: 'Rackspace Email', url: 'https://rackspace.com/email/{u}' },
  { name: 'FastMail', url: 'https://fastmail.com/{u}' },
  { name: 'Pobox', url: 'https://pobox.com/{u}' },
  { name: 'SpamSieve', url: 'https://spamsieve.com/{u}' },
  { name: 'SpamAssassin', url: 'https://spamassassin.apache.org/{u}' },
  { name: 'Rspamd', url: 'https://rspamd.com/{u}' },
  { name: 'Dovecot', url: 'https://dovecot.org/{u}' },
  { name: 'Postfix', url: 'https://postfix.org/{u}' },
  { name: 'Sendmail', url: 'https://sendmail.com/{u}' },
  { name: 'Exim', url: 'https://exim.org/{u}' },
  { name: 'OpenSMTPD', url: 'https://opensmtpd.org/{u}' },
  { name: 'Haraka', url: 'https://haraka.github.io/{u}' },
  { name: 'Mailcow', url: 'https://mailcow.email/{u}' },
  { name: 'Mailu', url: 'https://mailu.io/{u}' },
  { name: 'Docker Mailserver', url: 'https://docker-mailserver.github.io/{u}' },
  { name: 'WildDuck', url: 'https://wildduck.email/{u}' },
  { name: 'ZoneMTA', url: 'https://zonemta.com/{u}' },
  { name: 'Haraka', url: 'https://haraka.github.io/{u}' },
  { name: 'Slimta', url: 'https://slimta.org/{u}' },
  { name: 'KumoMTA', url: 'https://kumomta.com/{u}' },
  { name: 'Catapult', url: 'https://catapult.com/{u}' },
  { name: 'SocketLabs', url: 'https://socketlabs.com/{u}' },
  { name: 'SendGrid', url: 'https://sendgrid.com/{u}' },
  { name: 'Mailgun', url: 'https://mailgun.com/{u}' },
  { name: 'Postmark', url: 'https://postmarkapp.com/{u}' },
  { name: 'Amazon SES', url: 'https://aws.amazon.com/ses/{u}' },
  { name: 'Mailjet', url: 'https://mailjet.com/{u}' },
  { name: 'SparkPost', url: 'https://sparkpost.com/{u}' },
  { name: 'SendinBlue', url: 'https://sendinblue.com/{u}' },
  { name: 'MailerLite', url: 'https://mailerlite.com/{u}' },
  { name: 'Mailchimp', url: 'https://mailchimp.com/{u}' },
  { name: 'Constant Contact', url: 'https://constantcontact.com/{u}' },
  { name: 'AWeber', url: 'https://aweber.com/{u}' },
  { name: 'GetResponse', url: 'https://getresponse.com/{u}' },
  { name: 'ConvertKit', url: 'https://convertkit.com/{u}' },
  { name: 'Drip', url: 'https://drip.com/{u}' },
  { name: 'ActiveCampaign', url: 'https://activecampaign.com/{u}' },
  { name: 'HubSpot', url: 'https://hubspot.com/{u}' },
  { name: 'Salesforce', url: 'https://salesforce.com/{u}' },
  { name: 'Zoho CRM', url: 'https://zoho.com/crm/{u}' },
  { name: 'Pipedrive', url: 'https://pipedrive.com/{u}' },
  { name: 'Freshsales', url: 'https://freshsales.io/{u}' },
  { name: 'Copper', url: 'https://copper.com/{u}' },
  { name: 'Close', url: 'https://close.com/{u}' },
  { name: 'Stripe', url: 'https://stripe.com/{u}' },
  { name: 'PayPal', url: 'https://paypal.com/{u}' },
  { name: 'Square', url: 'https://square.com/{u}' },
  { name: 'Braintree', url: 'https://braintreepayments.com/{u}' },
  { name: 'Adyen', url: 'https://adyen.com/{u}' },
  { name: 'Plaid', url: 'https://plaid.com/{u}' },
  { name: 'Revolut', url: 'https://revolut.com/{u}' },
  { name: 'Wise', url: 'https://wise.com/{u}' },
  { name: 'N26', url: 'https://n26.com/{u}' },
  { name: 'Monzo', url: 'https://monzo.com/{u}' },
  { name: 'Starling', url: 'https://starlingbank.com/{u}' },
  { name: 'Chime', url: 'https://chime.com/{u}' },
  { name: 'Cash App', url: 'https://cash.app/{u}' },
  { name: 'Venmo', url: 'https://venmo.com/{u}' },
  { name: 'Zelle', url: 'https://zellepay.com/{u}' },
  { name: 'Bitcoin', url: 'https://bitcoin.org/{u}' },
  { name: 'Ethereum', url: 'https://ethereum.org/{u}' },
  { name: 'Coinbase', url: 'https://coinbase.com/{u}' },
  { name: 'Binance', url: 'https://binance.com/{u}' },
  { name: 'Kraken', url: 'https://kraken.com/{u}' },
  { name: 'Gemini', url: 'https://gemini.com/{u}' },
  { name: 'Crypto.com', url: 'https://crypto.com/{u}' },
  { name: 'Blockchain.com', url: 'https://blockchain.com/{u}' },
  { name: 'Etherscan', url: 'https://etherscan.io/{u}' },
  { name: 'Solscan', url: 'https://solscan.io/{u}' },
  { name: 'Polygonscan', url: 'https://polygonscan.com/{u}' },
  { name: 'BscScan', url: 'https://bscscan.com/{u}' },
  { name: 'Arbiscan', url: 'https://arbiscan.io/{u}' },
  { name: 'Optimistic Etherscan', url: 'https://optimistic.etherscan.io/{u}' },
  { name: 'Snowtrace', url: 'https://snowtrace.io/{u}' },
  { name: 'FTMScan', url: 'https://ftmscan.com/{u}' },
  { name: 'Celoscan', url: 'https://celoscan.io/{u}' },
  { name: 'Avascan', url: 'https://avascan.info/{u}' },
  { name: 'NearBlocks', url: 'https://nearblocks.io/{u}' },
  { name: 'SolanaFM', url: 'https://solana.fm/{u}' },
  { name: 'Terra Finder', url: 'https://finder.terra.money/{u}' },
  { name: 'Mintscan', url: 'https://mintscan.io/{u}' },
  { name: 'Big Dipper', url: 'https://bigdipper.live/{u}' },
  { name: 'Ping.pub', url: 'https://ping.pub/{u}' },
  { name: 'Stargazer', url: 'https://stargazer.com/{u}' },
  { name: 'Keplr', url: 'https://keplr.app/{u}' },
  { name: 'Leap Wallet', url: 'https://leapwallet.io/{u}' },
  { name: 'Cosmostation', url: 'https://cosmostation.io/{u}' },
  { name: 'Trust Wallet', url: 'https://trustwallet.com/{u}' },
  { name: 'MetaMask', url: 'https://metamask.io/{u}' },
  { name: 'Rainbow', url: 'https://rainbow.me/{u}' },
  { name: 'Phantom', url: 'https://phantom.app/{u}' },
  { name: 'Solflare', url: 'https://solflare.com/{u}' },
  { name: 'Backpack', url: 'https://backpack.app/{u}' },
  { name: 'Exodus', url: 'https://exodus.com/{u}' },
  { name: 'Electrum', url: 'https://electrum.org/{u}' },
  { name: 'Sparrow', url: 'https://sparrowwallet.com/{u}' },
  { name: 'BlueWallet', url: 'https://bluewallet.io/{u}' },
  { name: 'Wasabi Wallet', url: 'https://wasabiwallet.io/{u}' },
  { name: 'Samourai Wallet', url: 'https://samouraiwallet.com/{u}' },
  { name: 'Specter', url: 'https://specter.solutions/{u}' },
  { name: 'ColdCard', url: 'https://coldcard.com/{u}' },
  { name: 'Ledger', url: 'https://ledger.com/{u}' },
  { name: 'Trezor', url: 'https://trezor.io/{u}' },
  { name: 'KeepKey', url: 'https://keepkey.com/{u}' },
  { name: 'BitBox', url: 'https://bitbox.swiss/{u}' },
  { name: 'Cobo Vault', url: 'https://cobo.com/{u}' },
  { name: 'SafePal', url: 'https://safepal.com/{u}' },
  { name: 'NGRAVE', url: 'https://ngrave.io/{u}' },
  { name: 'SecurX', url: 'https://securx.io/{u}' },
  { name: 'Ellipal', url: 'https://ellipal.com/{u}' },
  { name: 'DCent', url: 'https://dcentwallet.com/{u}' },
  { name: 'Lattice1', url: 'https://gridplus.io/{u}' },
  { name: 'OneKey', url: 'https://onekey.so/{u}' },
  { name: 'Keystone', url: 'https://keyst.one/{u}' },
  { name: 'AirGap', url: 'https://airgap.it/{u}' },
  { name: 'Atoma', url: 'https://atoma.io/{u}' },
  { name: 'Web3', url: 'https://web3.com/{u}' },
  { name: 'ENS', url: 'https://ens.domains/{u}' },
  { name: 'Unstoppable Domains', url: 'https://unstoppabledomains.com/{u}' },
  { name: 'Handshake', url: 'https://handshake.org/{u}' },
  { name: 'Namebase', url: 'https://namebase.io/{u}' },
  { name: 'Freenom', url: 'https://freenom.com/{u}' },
  { name: 'Niagara', url: 'https://niagara.com/{u}' },
  { name: 'Epik', url: 'https://epik.com/{u}' },
  { name: 'Dynadot', url: 'https://dynadot.com/{u}' },
  { name: 'Porkbun', url: 'https://porkbun.com/{u}' },
  { name: 'Hover', url: 'https://hover.com/{u}' },
  { name: 'iwantmyname', url: 'https://iwantmyname.com/{u}' },
  { name: 'DNSimple', url: 'https://dnsimple.com/{u}' },
  { name: 'DNS Made Easy', url: 'https://dnsmadeeasy.com/{u}' },
  { name: 'Constellix', url: 'https://constellix.com/{u}' },
  { name: 'NS1', url: 'https://ns1.com/{u}' },
  { name: 'Neustar', url: 'https://neustar.com/{u}' },
  { name: 'UltraDNS', url: 'https://ultradns.com/{u}' },
  { name: 'Akamai DNS', url: 'https://akamai.com/dns/{u}' },
  { name: 'CloudFlare DNS', url: 'https://cloudflare.com/dns/{u}' },
  { name: 'Amazon Route53', url: 'https://aws.amazon.com/route53/{u}' },
  { name: 'Google Cloud DNS', url: 'https://cloud.google.com/dns/{u}' },
  { name: 'Azure DNS', url: 'https://azure.microsoft.com/dns/{u}' },
  { name: 'Oracle DNS', url: 'https://oracle.com/dns/{u}' },
  { name: 'IBM DNS', url: 'https://ibm.com/dns/{u}' },
  { name: 'Alibaba DNS', url: 'https://alibaba.com/dns/{u}' },
  { name: 'Tencent DNS', url: 'https://tencent.com/dns/{u}' },
  { name: 'Baidu DNS', url: 'https://baidu.com/dns/{u}' },
  { name: 'Yandex DNS', url: 'https://yandex.com/dns/{u}' },
  { name: 'Comodo DNS', url: 'https://comodo.com/dns/{u}' },
  { name: 'OpenDNS', url: 'https://opendns.com/{u}' },
  { name: 'Quad9', url: 'https://quad9.net/{u}' },
  { name: 'Cloudflare 1.1.1.1', url: 'https://1.1.1.1/{u}' },
  { name: 'Google 8.8.8.8', url: 'https://8.8.8.8/{u}' },
  { name: 'AdGuard DNS', url: 'https://adguard.com/dns/{u}' },
  { name: 'NextDNS', url: 'https://nextdns.io/{u}' },
  { name: 'ControlD', url: 'https://controld.com/{u}' },
  { name: 'Pi-hole', url: 'https://pi-hole.net/{u}' },
  { name: 'AdGuard Home', url: 'https://adguard.com/adguard-home/{u}' },
  { name: 'Blocky', url: 'https://blocky.com/{u}' },
  { name: 'Technitium', url: 'https://technitium.com/{u}' },
  { name: 'Unbound', url: 'https://nlnetlabs.nl/unbound/{u}' },
  { name: 'BIND', url: 'https://isc.org/bind/{u}' },
  { name: 'Knot DNS', url: 'https://knot-dns.cz/{u}' },
  { name: 'PowerDNS', url: 'https://powerdns.com/{u}' },
  { name: 'NSD', url: 'https://nlnetlabs.nl/nsd/{u}' },
  { name: 'CoreDNS', url: 'https://coredns.io/{u}' },
  { name: 'DNSdist', url: 'https://dnsdist.org/{u}' },
  { name: 'Dnsmasq', url: 'https://thekelleys.org.uk/dnsmasq/{u}' },
  { name: 'Stubby', url: 'https://dnsprivacy.org/{u}' },
  { name: 'DoH', url: 'https://doh.com/{u}' },
  { name: 'DoT', url: 'https://dot.com/{u}' },
  { name: 'DNSCrypt', url: 'https://dnscrypt.info/{u}' },
  { name: 'DNSSEC', url: 'https://dnssec.net/{u}' },
  { name: 'ICANN', url: 'https://icann.org/{u}' },
  { name: 'IETF', url: 'https://ietf.org/{u}' },
  { name: 'ISOC', url: 'https://isoc.org/{u}' },
  { name: 'ARIN', url: 'https://arin.net/{u}' },
  { name: 'RIPE', url: 'https://ripe.net/{u}' },
  { name: 'APNIC', url: 'https://apnic.net/{u}' },
  { name: 'LACNIC', url: 'https://lacnic.net/{u}' },
  { name: 'AfriNIC', url: 'https://afrinic.net/{u}' },
  { name: 'NRO', url: 'https://nro.net/{u}' },
  { name: 'IANA', url: 'https://iana.org/{u}' },
  { name: 'Internet Society', url: 'https://internetsociety.org/{u}' },
  { name: 'World Wide Web Consortium', url: 'https://w3.org/{u}' },
  { name: 'WHATWG', url: 'https://whatwg.org/{u}' },
  { name: 'ECMA', url: 'https://ecma-international.org/{u}' },
  { name: 'ISO', url: 'https://iso.org/{u}' },
  { name: 'IEEE', url: 'https://ieee.org/{u}' },
  { name: 'ITU', url: 'https://itu.int/{u}' },
  { name: 'ETSI', url: 'https://etsi.org/{u}' },
  { name: '3GPP', url: 'https://3gpp.org/{u}' },
  { name: 'GSMA', url: 'https://gsma.com/{u}' },
  { name: 'OASIS', url: 'https://oasis-open.org/{u}' },
  { name: 'OpenAPI', url: 'https://openapis.org/{u}' },
  { name: 'AsyncAPI', url: 'https://asyncapi.com/{u}' },
  { name: 'GraphQL', url: 'https://graphql.org/{u}' },
  { name: 'REST', url: 'https://restfulapi.net/{u}' },
  { name: 'gRPC', url: 'https://grpc.io/{u}' },
  { name: 'Protobuf', url: 'https://protobuf.dev/{u}' },
  { name: 'FlatBuffers', url: 'https://flatbuffers.dev/{u}' },
  { name: 'Capn Proto', url: 'https://capnproto.org/{u}' },
  { name: 'MessagePack', url: 'https://msgpack.org/{u}' },
  { name: 'JSON Schema', url: 'https://json-schema.org/{u}' },
  { name: 'JSON:API', url: 'https://jsonapi.org/{u}' },
  { name: 'HAL', url: 'https://hal.io/{u}' },
  { name: 'Siren', url: 'https://siren.com/{u}' },
  { name: 'Collection+JSON', url: 'https://collectionjson.com/{u}' },
  { name: 'JSON-LD', url: 'https://json-ld.org/{u}' },
  { name: 'RDF', url: 'https://rdf.com/{u}' },
  { name: 'SPARQL', url: 'https://sparql.com/{u}' },
  { name: 'OWL', url: 'https://owl.com/{u}' },
  { name: 'SHACL', url: 'https://shacl.com/{u}' },
  { name: 'Web Ontology', url: 'https://webontology.com/{u}' },
  { name: 'Schema.org', url: 'https://schema.org/{u}' },
  { name: 'OpenGraph', url: 'https://ogp.me/{u}' },
  { name: 'Twitter Cards', url: 'https://cards.twitter.com/{u}' },
  { name: 'oEmbed', url: 'https://oembed.com/{u}' },
  { name: 'ActivityPub', url: 'https://activitypub.rocks/{u}' },
  { name: 'Webmentions', url: 'https://webmention.io/{u}' },
  { name: 'Micropub', url: 'https://micropub.net/{u}' },
  { name: 'Microsub', url: 'https://microsub.net/{u}' },
  { name: 'IndieWeb', url: 'https://indieweb.org/{u}' },
  { name: 'Known', url: 'https://withknown.com/{u}' },
  { name: 'Micro.blog', url: 'https://micro.blog/{u}' },
  { name: 'WriteFreely', url: 'https://writefreely.org/{u}' },
  { name: 'Plume', url: 'https://plume.org/{u}' },
  { name: 'Misskey', url: 'https://misskey.io/{u}' },
  { name: 'Calckey', url: 'https://calckey.org/{u}' },
  { name: 'Firefish', url: 'https://firefish.dev/{u}' },
  { name: 'Pleroma', url: 'https://pleroma.social/{u}' },
  { name: 'Akkoma', url: 'https://akkoma.dev/{u}' },
  { name: 'Friendica', url: 'https://friendi.ca/{u}' },
  { name: 'Hubzilla', url: 'https://hubzilla.org/{u}' },
  { name: 'Streams', url: 'https://streams.com/{u}' },
  { name: 'Zot', url: 'https://zot.com/{u}' },
  { name: 'Nomad', url: 'https://nomad.com/{u}' },
  { name: 'Diaspora', url: 'https://diasporafoundation.org/{u}' },
  { name: 'SocialHome', url: 'https://socialhome.network/{u}' },
  { name: 'Minds', url: 'https://minds.com/{u}' },
  { name: 'Gab', url: 'https://gab.com/{u}' },
  { name: 'Parler', url: 'https://parler.com/{u}' },
  { name: 'Truth Social', url: 'https://truthsocial.com/{u}' },
  { name: 'Gettr', url: 'https://gettr.com/{u}' },
  { name: 'MeWe', url: 'https://mewe.com/{u}' },
  { name: 'CloutHub', url: 'https://clouthub.com/{u}' },
  { name: 'Spreely', url: 'https://spreely.com/{u}' },
  { name: 'Locals', url: 'https://locals.com/{u}' },
  { name: 'Brighteon', url: 'https://brighteon.com/{u}' },
  { name: 'BitChute', url: 'https://bitchute.com/{u}' },
  { name: 'Odysee', url: 'https://odysee.com/@{u}' },
  { name: 'LBRY', url: 'https://lbry.com/{u}' },
  { name: 'DTube', url: 'https://d.tube/{u}' },
  { name: 'Peertube', url: 'https://peertube.tv/{u}' },
  { name: 'Vimeo', url: 'https://vimeo.com/{u}' },
  { name: 'Dailymotion', url: 'https://dailymotion.com/{u}' },
  { name: 'Twitch', url: 'https://twitch.tv/{u}' },
  { name: 'Kick', url: 'https://kick.com/{u}' },
  { name: 'Trovo', url: 'https://trovo.live/{u}' },
  { name: 'DLive', url: 'https://dlive.tv/{u}' },
  { name: 'Theta', url: 'https://theta.tv/{u}' },
  { name: 'LiveCoin', url: 'https://livecoin.tv/{u}' },
  { name: 'Caffeine', url: 'https://caffeine.tv/{u}' },
  { name: 'Facebook Gaming', url: 'https://facebook.com/gaming/{u}' },
  { name: 'YouTube Gaming', url: 'https://gaming.youtube.com/{u}' },
  { name: 'Mixer', url: 'https://mixer.com/{u}' },
  { name: 'Smashcast', url: 'https://smashcast.tv/{u}' },
  { name: 'AfreecaTV', url: 'https://afreecatv.com/{u}' },
  { name: 'Douyu', url: 'https://douyu.com/{u}' },
  { name: 'Huya', url: 'https://huya.com/{u}' },
  { name: 'Bilibili', url: 'https://bilibili.com/{u}' },
  { name: 'Niconico', url: 'https://nicovideo.jp/{u}' },
  { name: 'Showroom', url: 'https://showroom-live.com/{u}' },
  { name: 'Pococha', url: 'https://pococha.com/{u}' },
  { name: 'IRIAM', url: 'https://iriam.com/{u}' },
  { name: 'Mildom', url: 'https://mildom.com/{u}' },
  { name: 'Bigolive', url: 'https://bigolive.com/{u}' },
  { name: 'LiveMe', url: 'https://liveme.com/{u}' },
  { name: 'Nonolive', url: 'https://nonolive.com/{u}' },
  { name: 'Uplive', url: 'https://uplive.com/{u}' },
  { name: 'Kitty Live', url: 'https://kittylive.com/{u}' },
  { name: 'Cube TV', url: 'https://cubetv.com/{u}' },
  { name: 'Muse', url: 'https://muse.com/{u}' },
  { name: 'Chill', url: 'https://chill.com/{u}' },
  { name: 'Boomerang', url: 'https://boomerang.com/{u}' },
  { name: 'Gaia', url: 'https://gaia.com/{u}' },
  { name: 'Tidal', url: 'https://tidal.com/{u}' },
  { name: 'Deezer', url: 'https://deezer.com/{u}' },
  { name: 'Qobuz', url: 'https://qobuz.com/{u}' },
  { name: 'Napster', url: 'https://napster.com/{u}' },
  { name: 'Pandora', url: 'https://pandora.com/{u}' },
  { name: 'iHeartRadio', url: 'https://iheart.com/{u}' },
  { name: 'Radio.com', url: 'https://radio.com/{u}' },
  { name: 'TuneIn', url: 'https://tunein.com/{u}' },
  { name: 'Audible', url: 'https://audible.com/{u}' },
  { name: 'Audioboom', url: 'https://audioboom.com/{u}' },
  { name: 'Podbean', url: 'https://podbean.com/{u}' },
  { name: 'Anchor', url: 'https://anchor.fm/{u}' },
  { name: 'Buzzsprout', url: 'https://buzzsprout.com/{u}' },
  { name: 'Transistor', url: 'https://transistor.fm/{u}' },
  { name: 'RedCircle', url: 'https://redcircle.com/{u}' },
  { name: 'Captivate', url: 'https://captivate.fm/{u}' },
  { name: 'Simplecast', url: 'https://simplecast.com/{u}' },
  { name: 'Fireside', url: 'https://fireside.fm/{u}' },
  { name: 'Megaphone', url: 'https://megaphone.fm/{u}' },
  { name: 'ART19', url: 'https://art19.com/{u}' },
  { name: 'Omny Studio', url: 'https://omnystudio.com/{u}' },
  { name: 'Acast', url: 'https://acast.com/{u}' },
  { name: 'RadioPublic', url: 'https://radiopublic.com/{u}' },
  { name: 'Breaker', url: 'https://breaker.com/{u}' },
  { name: 'Overcast', url: 'https://overcast.fm/{u}' },
  { name: 'Pocket Casts', url: 'https://pocketcasts.com/{u}' },
  { name: 'Castro', url: 'https://castro.fm/{u}' },
  { name: 'Apple Podcasts', url: 'https://podcasts.apple.com/{u}' },
  { name: 'Google Podcasts', url: 'https://podcasts.google.com/{u}' },
  { name: 'Spotify Podcasts', url: 'https://spotify.com/podcasts/{u}' },
  { name: 'Amazon Music', url: 'https://music.amazon.com/{u}' },
  { name: 'YouTube Music', url: 'https://music.youtube.com/{u}' },
  { name: 'Apple Music', url: 'https://music.apple.com/{u}' },
  { name: 'SoundCloud', url: 'https://soundcloud.com/{u}' },
  { name: 'Bandcamp', url: 'https://bandcamp.com/{u}' },
  { name: 'Mixcloud', url: 'https://mixcloud.com/{u}' },
  { name: 'Hearthis', url: 'https://hearthis.at/{u}' },
  { name: 'ReverbNation', url: 'https://reverbnation.com/{u}' },
  { name: 'Sonicbids', url: 'https://sonicbids.com/{u}' },
  { name: 'Viberate', url: 'https://viberate.com/{u}' },
  { name: 'Bandsintown', url: 'https://bandsintown.com/{u}' },
  { name: 'Songkick', url: 'https://songkick.com/{u}' },
  { name: 'Setlist.fm', url: 'https://setlist.fm/{u}' },
  { name: 'Discogs', url: 'https://discogs.com/{u}' },
  { name: 'MusicBrainz', url: 'https://musicbrainz.org/{u}' },
  { name: 'AllMusic', url: 'https://allmusic.com/{u}' },
  { name: 'RateYourMusic', url: 'https://rateyourmusic.com/{u}' },
  { name: 'Album of the Year', url: 'https://albumoftheyear.org/{u}' },
  { name: 'Metacritic', url: 'https://metacritic.com/{u}' },
  { name: 'Rotten Tomatoes', url: 'https://rottentomatoes.com/{u}' },
  { name: 'IMDb', url: 'https://imdb.com/{u}' },
  { name: 'TV Guide', url: 'https://tvguide.com/{u}' },
  { name: 'Trakt', url: 'https://trakt.tv/{u}' },
  { name: 'TVDB', url: 'https://thetvdb.com/{u}' },
  { name: 'TMDB', url: 'https://themoviedb.org/{u}' },
  { name: 'FilmAffinity', url: 'https://filmaffinity.com/{u}' },
  { name: 'Letterboxd', url: 'https://letterboxd.com/{u}' },
  { name: 'MyDramaList', url: 'https://mydramalist.com/{u}' },
  { name: 'Serializd', url: 'https://serializd.com/{u}' },
  { name: 'AniList', url: 'https://anilist.co/{u}' },
  { name: 'MyAnimeList', url: 'https://myanimelist.net/{u}' },
  { name: 'AniDB', url: 'https://anidb.net/{u}' },
  { name: 'Kitsu', url: 'https://kitsu.io/{u}' },
  { name: 'Otak Otaku', url: 'https://otakotaku.com/{u}' },
  { name: 'Anime-Planet', url: 'https://anime-planet.com/{u}' },
  { name: 'Crunchyroll', url: 'https://crunchyroll.com/{u}' },
  { name: 'Funimation', url: 'https://funimation.com/{u}' },
  { name: 'HIDIVE', url: 'https://hidive.com/{u}' },
  { name: 'VRV', url: 'https://vrv.co/{u}' },
  { name: 'RetroCrush', url: 'https://retrocrush.tv/{u}' },
  { name: 'Midnight Pulp', url: 'https://midnightpulp.com/{u}' },
  { name: 'Shout Factory', url: 'https://shoutfactory.com/{u}' },
  { name: 'Criterion Channel', url: 'https://criterionchannel.com/{u}' },
  { name: 'Mubi', url: 'https://mubi.com/{u}' },
  { name: 'Kanopy', url: 'https://kanopy.com/{u}' },
  { name: 'Hoopla', url: 'https://hoopladigital.com/{u}' },
  { name: 'Tubi', url: 'https://tubitv.com/{u}' },
  { name: 'Pluto TV', url: 'https://pluto.tv/{u}' },
  { name: 'Peacock', url: 'https://peacocktv.com/{u}' },
  { name: 'Paramount+', url: 'https://paramountplus.com/{u}' },
  { name: 'HBO Max', url: 'https://hbomax.com/{u}' },
  { name: 'Discovery+', url: 'https://discoveryplus.com/{u}' },
  { name: 'Apple TV+', url: 'https://tv.apple.com/{u}' },
  { name: 'Amazon Prime Video', url: 'https://primevideo.com/{u}' },
  { name: 'Netflix', url: 'https://netflix.com/{u}' },
  { name: 'Hulu', url: 'https://hulu.com/{u}' },
  { name: 'Disney+', url: 'https://disneyplus.com/{u}' },
  { name: 'ESPN+', url: 'https://espnplus.com/{u}' },
  { name: 'Star+', url: 'https://starplus.com/{u}' },
  { name: 'DAZN', url: 'https://dazn.com/{u}' },
  { name: 'F1 TV', url: 'https://f1tv.com/{u}' },
  { name: 'NBA League Pass', url: 'https://nba.com/leaguepass/{u}' },
  { name: 'NFL Game Pass', url: 'https://nfl.com/gamepass/{u}' },
  { name: 'MLB.tv', url: 'https://mlb.tv/{u}' },
  { name: 'NHL.tv', url: 'https://nhl.tv/{u}' },
  { name: 'UFC Fight Pass', url: 'https://ufcfightpass.com/{u}' },
  { name: 'WWE Network', url: 'https://wwenetwork.com/{u}' },
  { name: 'AEW Plus', url: 'https://aewplus.com/{u}' },
  { name: 'FITE', url: 'https://fite.tv/{u}' },
  { name: 'Triller', url: 'https://triller.com/{u}' },
  { name: 'Twitch', url: 'https://twitch.tv/{u}' },
  { name: 'YouTube', url: 'https://youtube.com/@{u}' },
  { name: 'Vimeo', url: 'https://vimeo.com/{u}' },
  { name: 'Dailymotion', url: 'https://dailymotion.com/{u}' },
  { name: 'Facebook Watch', url: 'https://facebook.com/watch/{u}' },
  { name: 'Instagram TV', url: 'https://instagram.com/tv/{u}' },
  { name: 'TikTok', url: 'https://tiktok.com/@{u}' },
  { name: 'Snapchat', url: 'https://snapchat.com/{u}' },
  { name: 'Telegram', url: 'https://t.me/{u}' },
  { name: 'Signal', url: 'https://signal.me/{u}' },
  { name: 'WhatsApp', url: 'https://wa.me/{u}' },
  { name: 'WeChat', url: 'https://wechat.com/{u}' },
  { name: 'QQ', url: 'https://qq.com/{u}' },
  { name: 'Weibo', url: 'https://weibo.com/{u}' },
  { name: 'Douyin', url: 'https://douyin.com/{u}' },
  { name: 'Kuaishou', url: 'https://kuaishou.com/{u}' },
  { name: 'Xiaohongshu', url: 'https://xiaohongshu.com/{u}' },
  { name: 'Zhihu', url: 'https://zhihu.com/{u}' },
  { name: 'Bilibili', url: 'https://bilibili.com/{u}' },
  { name: 'AcFun', url: 'https://acfun.cn/{u}' },
  { name: 'Tieba', url: 'https://tieba.baidu.com/{u}' },
  { name: 'Douban', url: 'https://douban.com/{u}' },
  { name: 'Jianshu', url: 'https://jianshu.com/{u}' },
  { name: 'CSDN', url: 'https://csdn.net/{u}' },
  { name: 'SegmentFault', url: 'https://segmentfault.com/{u}' },
  { name: 'V2EX', url: 'https://v2ex.com/{u}' },
  { name: 'Ruby China', url: 'https://ruby-china.org/{u}' },
  { name: 'Elixir Forum', url: 'https://elixirforum.com/{u}' },
  { name: 'Erlang Forums', url: 'https://erlangforums.com/{u}' },
  { name: 'Rust Forum', url: 'https://rust-forum.com/{u}' },
  { name: 'Go Forum', url: 'https://forum.golangbridge.org/{u}' },
  { name: 'Python Forum', url: 'https://python-forum.io/{u}' },
  { name: 'JavaScript Forum', url: 'https://javascriptforum.com/{u}' },
  { name: 'TypeScript Forum', url: 'https://typescriptforum.com/{u}' },
  { name: 'Frontend Forum', url: 'https://frontendforum.com/{u}' },
  { name: 'Backend Forum', url: 'https://backendforum.com/{u}' },
  { name: 'DevOps Forum', url: 'https://devopsforum.com/{u}' },
  { name: 'Cloud Forum', url: 'https://cloudforum.com/{u}' },
  { name: 'Security Forum', url: 'https://securityforum.com/{u}' },
  { name: 'OSINT Forum', url: 'https://osintforum.com/{u}' },
  { name: 'Hacking Forum', url: 'https://hackingforum.com/{u}' },
  { name: 'Pentesting Forum', url: 'https://pentestingforum.com/{u}' },
  { name: 'CTF Forum', url: 'https://ctfforum.com/{u}' },
  { name: 'Bug Bounty Forum', url: 'https://bugbountyforum.com/{u}' },
  { name: 'Vulnerability Research', url: 'https://vulnresearch.com/{u}' },
  { name: 'Exploit Forum', url: 'https://exploitforum.com/{u}' },
  { name: 'Malware Forum', url: 'https://malwareforum.com/{u}' },
  { name: 'Ransomware Forum', url: 'https://ransomwareforum.com/{u}' },
  { name: 'Phishing Forum', url: 'https://phishingforum.com/{u}' },
  { name: 'Spam Forum', url: 'https://spamforum.com/{u}' },
  { name: 'Crypto Forum', url: 'https://cryptoforum.com/{u}' },
  { name: 'Darknet Forum', url: 'https://darknetforum.com/{u}' },
  { name: 'Deep Web Forum', url: 'https://deepwebforum.com/{u}' },
  { name: 'Tor Forum', url: 'https://torforum.com/{u}' },
  { name: 'I2P Forum', url: 'https://i2pforum.com/{u}' },
  { name: 'Freenet Forum', url: 'https://freenetforum.com/{u}' },
  { name: 'ZeroNet Forum', url: 'https://zeronetforum.com/{u}' },
  { name: 'Loki Forum', url: 'https://lokiforum.com/{u}' },
  { name: 'Session Forum', url: 'https://sessionforum.com/{u}' },
  { name: 'Matrix Forum', url: 'https://matrixforum.com/{u}' },
  { name: 'IRC Forum', url: 'https://ircforum.com/{u}' },
  { name: 'XMPP Forum', url: 'https://xmppforum.com/{u}' },
  { name: 'Fediverse Forum', url: 'https://fediverseforum.com/{u}' },
  { name: 'ActivityPub Forum', url: 'https://activitypubforum.com/{u}' },
];

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const username = searchParams.get('username');
  if (!username) return NextResponse.json({ error: 'Missing username parameter' }, { status: 400 });

  const maxPlatforms = Math.min(parseInt(searchParams.get('max') || '200'), 500);
  const selected = PLATFORMS.slice(0, maxPlatforms);

  const batchSize = 20;
  const results: any[] = [];

  for (let i = 0; i < selected.length; i += batchSize) {
    const batch = selected.slice(i, i + batchSize);
    const batchResults = await Promise.allSettled(
      batch.map(async (p) => {
        try {
          const url = p.url.replace('{u}', encodeURIComponent(username));
          const resp = await fetch(url, { method: 'HEAD', signal: AbortSignal.timeout(4000) });
          const exists = resp.ok || resp.status === 403 || resp.status === 429 || resp.status === 401;
          return { name: p.name, url, exists, status: resp.status };
        } catch {
          return { name: p.name, url: p.url.replace('{u}', encodeURIComponent(username)), exists: null, status: 0 };
        }
      })
    );
    for (const r of batchResults) {
      if (r.status === 'fulfilled') results.push(r.value);
    }
  }

  const found = results.filter(r => r.exists === true);
  const maybe = results.filter(r => r.exists === null);

  return NextResponse.json({
    username,
    total_checked: results.length,
    platforms_found: found.length,
    maybe: maybe.length,
    results: results,
    timestamp: new Date().toISOString(),
  });
}